#ifndef RPTOGETHER_SERVER_CONFIG_HPP
#define RPTOGETHER_SERVER_CONFIG_HPP

#define RPT_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define RPT_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define RPT_VERSION_PATCH @PROJECT_VERSION_PATCH@

#define RPT_VERSION "@PROJECT_VERSION@"

#define RPT_RUNTIME_PLATFORM @RPT_TARGET_PLATFORM@

#endif // RPTOGETHER_SERVER_CONFIG_HPP
