#ifndef RPTOGETHER_SERVER_CONFIG_HPP
#define RPTOGETHER_SERVER_CONFIG_HPP

#include <string_view>

#define RPT_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define RPT_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define RPT_VERSION_PATCH @PROJECT_VERSION_PATCH@

constexpr std::string_view RPT_VERSION { "@PROJECT_VERSION@" };

#endif // RPTOGETHER_SERVER_CONFIG_HPP
